version: "3.10"

services:
  app:
    container_name: srcbot
    build: .
    command: bash bash.sh
    environment:
      API_ID: # Your API HASH from my.telegram.org
      API_HASH: # Your API ID from my.telegram.org
      BOT_TOKEN: # Bot token, get it from @BotFather
      BIN_CHANNEL: # The BIN Channel ID. Read the readme for more info about this var
      DATABASE_URL: # MongoDB URI for saving User IDs when they first Start the Bot. We will use that for Broadcasting to them. I will try to add more features related with Database. If you need help search for a tutorial on youtbe
      OWNER_ID: # Your Telegram User ID  like 1234509
      UPDATES_CHANNEL: # Put a Public Channel Username  without @, so every user have to Join that channel to use the bot. Must add bot to channel as Admin to work properly.IF DONT WANT KEEP VALUE AS None
      OWNER_USERNAME: # Enter your username without @  example  adarsh
